name: Docker Image CI

on:
  push:
    branches: [ main2 ] #[main] 分支对应上分 in 后面的 才能触发
  pull_request:
    branches: [ main2 ] #[main] 分支对应上分 in 后面的 才能触发

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      # 配置登录信息，secrets 变量在 github settings -> secrets 中设置
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # 构建镜像并上传到DOCKER容器镜像仓库 (自行百度创建自己的镜像仓库)
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: 1028414973/openai:1


      
      
